FROM centos:7
ENV HOME /
RUN yum update -y && \
    yum install -y \
        gcc-c++ \
        make \
        redhat-rpm-config \
        rpm-build \
        rpmdevtools \
        tar && \
    yum clean all && \
    rpmdev-setuptree
RUN echo '%dist .el7.jp3cki' >> /.rpmmacros
ADD ./rpmbuild/ /rpmbuild/
RUN chown -R root:root /rpmbuild
RUN rpmbuild -ba /rpmbuild/SPECS/brotli.spec
RUN tar -czf /tmp/brotli.tar.gz -C /rpmbuild RPMS SRPMS
CMD ["/bin/true"]
